site_name: Skyrage
repo_url: https://github.com/CorbeauBaptiste/Skyrage
repo_name: CorbeauBaptiste/Skyrage

nav:
  - Accueil: index.md

theme:
  name: material

plugins:
  # Extensions pour le thème Material
  - search

  # Extensions pour le Markdown
  - mkdocs_pymdownx_material_extras

  # Extension pour exporter le site en PDF
  - exporter

  # Minification du code HTML, CSS et JavaScript
  - minify:
      minify_html: true